# Generated by Django 5.0.3 on 2024-03-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
