# Generated by Django 5.0.3 on 2024-04-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='phone',
            field=models.IntegerField(default=1234567890),
        ),
    ]
